services:
  - docker

script:
- docker build --target test --tag test-image .
- docker run test-image test/unit
- docker run test-image test/integration
- docker run -e BOARD_ID -e KEY -e TOKEN test-image test/e2e