services:
- docker
script:
- docker build --target test --tag test-image .
- docker run test-image test/unit
- docker run test-image test/integration
- docker run -e BOARD_ID -e KEY -e TOKEN test-image test/e2e
notifications:
  slack:
    secure: ngugQw6OQv7E+xFYHlVg73l3hpRvJS7tH3gpriQ4GRhpGPmzb791A/AgTRZayPVmq07mxt5qkHq+e+Tti9DPO0+aQDHz9LrRBv1FtttKPA3z207bq3FuBzegVAQ/jUCzdN7FW/2rs/St8veQkH7h3bHDZRDSMLxaRH/eBEu/lRWhL/o5sSvS8M71ceuoQFKeXM/2BmE/5Xtgx7RrDnMbDQ9y/NqbcMn5xEJQQCx6ccGgxq+pKhK/w3060ea1paRuavuccMxnEMEar7yt4rk1w2CYJ1pwqrvu3soc1SrKOOCWZ8+gImdZ1WVZ7TFf9l12UNLU1Mkg9Lucj4MgNPXC3qHxX67oyPpV+Jxe6LDCK/XOdTSisC0Qn68enqw2mH+DePzJ8kq6umfyCHTj4NMlUj1NaT8FaJrUa8UWXXVvc5aCZIWzFO3yA6mpFU5CDAgT31NazhH5lwkMZqmfc88gKVq+JROayZOLzJdB4U9HV7Qe0/bFMQ8GPp/9B2IKHxuegGilbfdedkhTk5ad2wAAMSvbApoHvp8P86dv8MSaaa+bAOyWXrtX2c0Bz56ZEQ2aaGSKdo7PDEgC7fti0W8XN1YeLQ/ZCseq/tYDVgtQHDMoCW0EQtWrsEYH88ewLz+sNqQi6ekIPnxE+V6Gp74aDQngCEL62wLvjUQJomAtCW4=
  email:
    recipients:
      secure: Hyne62f+NFf1/8XESXdNkVacqC6zNwk5B/igj1H70Zg/2CNVV2cjoYV4UzQxi69sKuEbx9QgMWYXIQ84KEFNTDuNVEeohex0FRUJ2a+pEDL5F0bmKkJ6Bh1bRHp+wTXlE5l8N4gPDwSpkxPP98R3SwJBEm9qqpS9wRMxl3us40dMrqywTrsbISKD4Zxv4GJocl7heS5vVQx2Kse59RvZ3INm5g8fVeTvSV3W732T/FB7dFiK+xhC5lrD7JOtNIqCztpk/+m8S7hjasuZgNDsqO1UNujnSs7g7NmhD8Uo025PeyVDHYZZRFH+dor+fRI37yOeiAnvAIDqZBVCYHbeGSet4UoYWf1kmcuDGh9c4za3jKDvJ+sjQ+XNQv8rinR169iO9aYxshOnDw28/EVKaVq/7/UB3/OF8d+qV+yF4+nTERXGARyfjdjzqE3CJLBzS98hRPe75EEcofLxUyEO9IMKJY5O1HtcnpuRWvfCJWvC68oGch1PMUIdWMNA9vTJ5r51dx6DObXUnazueRnWBYlVWsHuGKuBUawLf7inE5ILaH9jEyODeidS2KlRUHvSdg8DE/Rr5r0gFXS4x+6tvf49tCaNPTgaRtETy17p3t94ttgk4Gs022S5gwfpqltQCyhXM7wUitPY8P5UDUmRzPoZ+Q33vDRTKNsoYBD1NtI=
    on_failure: always
    on_success: never  
