version: "3.3"
services:
  app:
    image: todo-app:dev
    ports:
      - 5000:5000
    env_file: 
      - .env.test
    depends_on: 
      - mongo
    networks: 
      - db
    volumes:
      - type: bind
        source: ./
        target: /app
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test_db_name
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks: 
      - db

networks: 
  db:
    driver: bridge

volumes:
  mongodbdata:
    driver: local